### CREATE a new user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "email": "test2@example.com",
  "username": "testuser2"
}

> {%
    client.global.set("user_uuid", response.body.uuid);
 %}

### GET user by UUID
GET {{baseUrl}}/users/id/{{user_uuid}}

### GET user by email
GET {{baseUrl}}/users/email/test@example.com

### GET user by username
GET {{baseUrl}}/users/username/testuser